import { afterEach, expect, it, vi } from "vitest";
import { createMapRenderer } from "../src/modules/map/renderer";
import { EMPTY_OVERLAY } from "../src/modules/map/travel";
import type { MapSystem } from "../src/modules/map/model";
afterEach(() => vi.unstubAllGlobals());
it("coalesces input and draws thousands of stars in bounded batches without repeated text measurement", () => {
 let overlay=EMPTY_OVERLAY;
 let callback: FrameRequestCallback = () => {}; let dragging = true;
 const raf = vi.fn((cb: FrameRequestCallback) => { callback=cb; return 1; });
 vi.stubGlobal("requestAnimationFrame",raf);vi.stubGlobal("cancelAnimationFrame",vi.fn());
 vi.stubGlobal("window",{devicePixelRatio:1});vi.stubGlobal("document",{documentElement:{}});
 vi.stubGlobal("getComputedStyle",()=>({color:"white",getPropertyValue:()=>"green"}));
 vi.stubGlobal("ResizeObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("MutationObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("Path2D",class {rect(){} moveTo(){} lineTo(){}});
 const ctx={createRadialGradient:vi.fn(()=>({addColorStop:vi.fn()})),measureText:vi.fn(()=>({width:60})),setTransform:vi.fn(),clearRect:vi.fn(),fill:vi.fn(),fillText:vi.fn(),beginPath:vi.fn(),arc:vi.fn(),stroke:vi.fn(),save:vi.fn(),restore:vi.fn(),moveTo:vi.fn(),lineTo:vi.fn()};
 const canvas={clientWidth:1000,clientHeight:700,getContext:()=>ctx} as unknown as HTMLCanvasElement;
 const systems:MapSystem[]=Array.from({length:8490},(_,i)=>[i,`System ${i}`,i%3===0?.8:i%3===1?.2:-.5,i%100,Math.floor(i/100),0]);
 const renderer=createMapRenderer(canvas,systems,{overlay:()=>overlay,camera:()=>({yaw:0,pitch:0,zoom:1}),dragging:()=>dragging,selected:null,query:"",labels:true,format:String,onHits:vi.fn()});
 for(let i=0;i<100;i++)renderer.schedule();
 expect(raf).toHaveBeenCalledTimes(1);
 callback(0); expect(ctx.fill.mock.calls.length).toBeLessThanOrEqual(6);expect(ctx.fillText).not.toHaveBeenCalled();
 expect(ctx.measureText).toHaveBeenCalledTimes(8490);
 dragging=false;renderer.schedule();callback(16);
 expect(ctx.measureText).toHaveBeenCalledTimes(8490);expect(ctx.fillText).toHaveBeenCalled();
 expect(ctx.fillText.mock.calls.length).toBeLessThanOrEqual(100);
 overlay={...EMPTY_OVERLAY,inRange:[0]};renderer.schedule();callback(32);
  expect(ctx.measureText).toHaveBeenCalledTimes(8490);
 overlay={...EMPTY_OVERLAY,route:Array.from({length:100},(_,i)=>i)};renderer.schedule();
 const linearLookups=vi.spyOn(Array.prototype,"find");callback(100);
 const scans=linearLookups.mock.calls.length;linearLookups.mockRestore();expect(scans).toBe(0);
 expect(ctx.createRadialGradient).toHaveBeenCalledTimes(1);
 expect(ctx.lineTo).not.toHaveBeenCalled();
 const framesBefore=raf.mock.calls.length;
 callback(500);expect(raf.mock.calls.length).toBe(framesBefore+1);
 callback(3100);expect(raf.mock.calls.length).toBe(framesBefore+2);
 renderer.destroy();
});

it("keeps jump destinations bright across region boundaries and prioritizes region labels", () => {
 let callback: FrameRequestCallback = () => {};
 vi.stubGlobal("requestAnimationFrame",(cb:FrameRequestCallback)=>{callback=cb;return 1;});vi.stubGlobal("cancelAnimationFrame",vi.fn());
 vi.stubGlobal("window",{devicePixelRatio:1});vi.stubGlobal("document",{documentElement:{}});
 vi.stubGlobal("getComputedStyle",()=>({color:"white",getPropertyValue:()=>"green"}));
 vi.stubGlobal("ResizeObserver",class {observe(){} disconnect(){}});vi.stubGlobal("MutationObserver",class {observe(){} disconnect(){}});
 class Path {rects:number[][]=[];rect(...args:number[]){this.rects.push(args);}moveTo(){}lineTo(){}}
 vi.stubGlobal("Path2D",Path);
 const batches:{alpha:number;rects:number[][]}[]=[];
 const ctx={globalAlpha:1,measureText:vi.fn(()=>({width:60})),setTransform:vi.fn(),clearRect:vi.fn(),fill:vi.fn(),fillText:vi.fn(),beginPath:vi.fn(),arc:vi.fn(),stroke:vi.fn()};
 ctx.fill.mockImplementation((path:Path)=>{batches.push({alpha:ctx.globalAlpha,rects:path.rects});});
 const canvas={clientWidth:1000,clientHeight:700,getContext:()=>ctx} as unknown as HTMLCanvasElement;
 const systems:MapSystem[]=[[1,"Origin",.8,0,0,0,100],[2,"Destination",.8,3,0,0,101],[3,"Background",.8,-3,0,0,101]];
 const renderer=createMapRenderer(canvas,systems,{overlay:()=>({...EMPTY_OVERLAY,inRange:[2]}),camera:()=>({yaw:0,pitch:0,zoom:.15}),dragging:()=>false,selected:null,query:"",labels:true,regions:[[100,"One"],[101,"Two"]],regionId:100,regionLabels:true,format:String,onHits:vi.fn()});
 callback(0);
 expect(batches.find(b=>b.rects.some(r=>r[0]>700))?.alpha).toBe(.85);
 expect(batches.find(b=>b.rects.some(r=>r[0]<300))?.alpha).toBe(.35);
 expect(ctx.fillText.mock.calls.some(call=>call[0]==="One")).toBe(true);
 expect(ctx.fillText.mock.calls.some(call=>String(call[0]).includes("Origin"))).toBe(false);
 const measured=ctx.measureText.mock.calls.length;renderer.schedule();callback(16);
 expect(ctx.measureText.mock.calls.length).toBe(measured);renderer.destroy();
});

it("fits a selected region independently of distant systems in all space", () => {
 let callback: FrameRequestCallback = () => {};
 vi.stubGlobal("requestAnimationFrame",(cb:FrameRequestCallback)=>{callback=cb;return 1;});vi.stubGlobal("cancelAnimationFrame",vi.fn());
 vi.stubGlobal("window",{devicePixelRatio:1});vi.stubGlobal("document",{documentElement:{}});
 vi.stubGlobal("getComputedStyle",()=>({color:"white",getPropertyValue:()=>"green"}));
 vi.stubGlobal("ResizeObserver",class {observe(){} disconnect(){}});vi.stubGlobal("MutationObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("Path2D",class {rect(){}moveTo(){}lineTo(){}});
 const ctx={measureText:()=>({width:60}),setTransform(){},clearRect(){},fill(){},fillText(){},beginPath(){},arc(){},stroke(){}};
 const canvas={clientWidth:1000,clientHeight:700,getContext:()=>ctx} as unknown as HTMLCanvasElement;
 let hits:{system:MapSystem;x:number;y:number}[]=[];
 const renderer=createMapRenderer(canvas,[[1,"A",.8,-6,0,0,100],[2,"B",.8,6,0,0,100],[3,"Far",.8,1459,0,0,101]],{camera:()=>({yaw:0,pitch:0,zoom:1}),dragging:()=>false,selected:null,query:"",labels:false,regionId:100,format:String,onHits:rows=>{hits=rows;}});
 callback(0);
 const a=hits.find(h=>h.system[0]===1)!, b=hits.find(h=>h.system[0]===2)!;
 expect(b.x-a.x).toBeCloseTo(560);expect(a.x).toBeGreaterThan(0);expect(b.x).toBeLessThan(1000);
 renderer.destroy();
});it("centers and fits the entire route independently of a selected origin and distant systems", () => {
 let callback: FrameRequestCallback = () => {};
 vi.stubGlobal("requestAnimationFrame",(cb:FrameRequestCallback)=>{callback=cb;return 1;});vi.stubGlobal("cancelAnimationFrame",vi.fn());
 vi.stubGlobal("window",{devicePixelRatio:1});vi.stubGlobal("document",{documentElement:{}});
 vi.stubGlobal("getComputedStyle",()=>({color:"white",getPropertyValue:()=>"green"}));
 vi.stubGlobal("ResizeObserver",class {observe(){} disconnect(){}});vi.stubGlobal("MutationObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("Path2D",class {rect(){}moveTo(){}lineTo(){}});
 const ctx={measureText:()=>({width:60}),setTransform(){},clearRect(){},fill(){},fillText(){},beginPath(){},arc(){},stroke(){}};
 const canvas={clientWidth:1000,clientHeight:700,getContext:()=>ctx} as unknown as HTMLCanvasElement;
 let hits:{system:MapSystem;x:number;y:number}[]=[];
 const renderer=createMapRenderer(canvas,[[1,"A",.8,-6,0,0,100],[2,"B",.8,6,0,0,100],[3,"Far",.8,1459,0,0,101]],{camera:()=>({yaw:0,pitch:0,zoom:1}),dragging:()=>false,selected:1,query:"",labels:false,focusRoute:[1,2],format:String,onHits:rows=>{hits=rows;}});
 callback(0);
 const a=hits.find(h=>h.system[0]===1)!, b=hits.find(h=>h.system[0]===2)!;
 expect(b.x-a.x).toBeCloseTo(560);expect(a.x).toBeGreaterThan(0);expect(b.x).toBeLessThan(1000);
 renderer.destroy();
});