import { afterEach, expect, it, vi } from "vitest";
import { createMapRenderer } from "../src/modules/map/renderer";
import { EMPTY_OVERLAY } from "../src/modules/map/travel";
import type { MapSystem } from "../src/modules/map/model";
afterEach(() => vi.unstubAllGlobals());
it("coalesces input and draws thousands of stars in bounded batches without repeated text measurement", () => {
 let overlay=EMPTY_OVERLAY;
 let callback: FrameRequestCallback = () => {}; let dragging = true;
 const raf = vi.fn((cb: FrameRequestCallback) => { callback=cb; return 1; });
 vi.stubGlobal("requestAnimationFrame",raf);vi.stubGlobal("cancelAnimationFrame",vi.fn());
 vi.stubGlobal("window",{devicePixelRatio:1});vi.stubGlobal("document",{documentElement:{}});
 vi.stubGlobal("getComputedStyle",()=>({color:"white",getPropertyValue:()=>"green"}));
 vi.stubGlobal("ResizeObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("MutationObserver",class {observe(){} disconnect(){}});
 vi.stubGlobal("Path2D",class {rect(){} moveTo(){} lineTo(){}});
 const ctx={createRadialGradient:vi.fn(()=>({addColorStop:vi.fn()})),measureText:vi.fn(()=>({width:60})),setTransform:vi.fn(),clearRect:vi.fn(),fill:vi.fn(),fillText:vi.fn(),beginPath:vi.fn(),arc:vi.fn(),stroke:vi.fn(),save:vi.fn(),restore:vi.fn(),moveTo:vi.fn(),lineTo:vi.fn()};
 const canvas={clientWidth:1000,clientHeight:700,getContext:()=>ctx} as unknown as HTMLCanvasElement;
 const systems:MapSystem[]=Array.from({length:8490},(_,i)=>[i,`System ${i}`,i%3===0?.8:i%3===1?.2:-.5,i%100,Math.floor(i/100),0]);
 const renderer=createMapRenderer(canvas,systems,{overlay:()=>overlay,camera:()=>({yaw:0,pitch:0,zoom:1}),dragging:()=>dragging,selected:null,query:"",labels:true,format:String,onHits:vi.fn()});
 for(let i=0;i<100;i++)renderer.schedule();
 expect(raf).toHaveBeenCalledTimes(1);
 callback(0); expect(ctx.fill.mock.calls.length).toBeLessThanOrEqual(6);expect(ctx.fillText).not.toHaveBeenCalled();
 expect(ctx.measureText).toHaveBeenCalledTimes(8490);
 dragging=false;renderer.schedule();callback(16);
 expect(ctx.measureText).toHaveBeenCalledTimes(8490);expect(ctx.fillText).toHaveBeenCalled();
 expect(ctx.fillText.mock.calls.length).toBeLessThanOrEqual(100);
 overlay={...EMPTY_OVERLAY,inRange:[0]};renderer.schedule();callback(32);
  expect(ctx.measureText).toHaveBeenCalledTimes(8490);
 overlay={...EMPTY_OVERLAY,route:[0,1,2]};renderer.schedule();callback(100);
 expect(ctx.createRadialGradient).toHaveBeenCalledTimes(1);
 expect(ctx.lineTo).not.toHaveBeenCalled();
 const framesBefore=raf.mock.calls.length;
 callback(500);expect(raf.mock.calls.length).toBe(framesBefore+1);
 callback(3100);expect(raf.mock.calls.length).toBe(framesBefore+2);
 renderer.destroy();
});
